export type Bill = {
  billNo: string;
  date: string;
  billTo: string;
  shipTo: string;
  placeOfSupply?: string;
  stateCode?: string;
  gstin?: string;
  workOrderNo?: string;
  itemDescription: string;
  invoiceDescription?: string;
  hsnSac?: string;
  amount: number;
  cgstPercent: number;
  sgstPercent: number;
  cgstAmount: number;
  sgstAmount: number;
  totalAmount: number;
  totalAmountInWords?: string;
};
